"""create_initial_schema

Revision ID: 659fbabd6579
Revises: 
Create Date: 2025-10-31 23:21:34.584957+05:30

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '659fbabd6579'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
