"""create_initial_schema

Revision ID: 1ce99acd8ec3
Revises: 659fbabd6579
Create Date: 2025-10-31 23:28:36.490038+05:30

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ce99acd8ec3'
down_revision = '659fbabd6579'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
