from pydantic import BaseModel, Field
from typing import Optional
from datetime import date, datetime

from src.modules.patients.encounter_schemas import EncounterRead

# --- Base Schema (Common fields) ---
class PatientBase(BaseModel):
    """Base Pydantic model for Patient, defines common fields."""
    full_name: str
    date_of_birth: Optional[date] = None
    contact_info: Optional[str] = None

# --- Schema for Creating a Patient (ID is generated by backend) ---
class PatientCreate(PatientBase):
    """
    Data required to register a new patient.
    The ID is generated by the service, so it's not included here.
    """
    pass # No extra fields needed beyond PatientBase

# --- Schema for Updating Patient Data ---
class PatientUpdate(BaseModel):
    """Pydantic model for updating a patient's info (all fields optional)."""
    full_name: Optional[str] = None
    date_of_birth: Optional[date] = None
    contact_info: Optional[str] = None

# --- Schema for Reading Patient Data (sent to client) ---
class PatientRead(PatientBase):
    """
    Data sent back to the client when reading patient info.
    Includes the generated ID and timestamps.
    """
    id: str # The custom-generated patient ID
    gender: Optional[str] = None
    blood_group: Optional[str] = None
    phone_number: Optional[str] = None
    emergency_contact: Optional[str] = None
    known_allergies: Optional[str] = None
    risk_flags: Optional[str] = None
    ward: Optional[str] = None
    bed_number: Optional[str] = None
    registration_timestamp: datetime
    created_at: datetime
    encounters: list[EncounterRead] = Field(default_factory=list)

    class Config:
        from_attributes = True # Enable ORM mode (SQLAlchemy -> Pydantic)
