# app/schemas/patient.py
from pydantic import BaseModel, Field
from typing import Optional
from datetime import date, datetime

# --- Base Schema (Common fields) ---
class PatientBase(BaseModel):
    """Base Pydantic model for Patient, defines common fields."""
    full_name: str
    date_of_birth: Optional[date] = None
    contact_info: Optional[str] = None

# --- Schema for Creating a Patient (ID is generated by backend) ---
class PatientCreate(PatientBase):
    """
    Data required to register a new patient.
    The ID is generated by the service, so it's not included here.
    """
    pass # No extra fields needed beyond PatientBase

# --- Schema for Updating Patient Data ---
class PatientUpdate(BaseModel):
    """Pydantic model for updating a patient's info (all fields optional)."""
    full_name: Optional[str] = None
    date_of_birth: Optional[date] = None
    contact_info: Optional[str] = None

# --- Schema for Reading Patient Data (sent to client) ---
class PatientRead(PatientBase):
    """
    Data sent back to the client when reading patient info.
    Includes the generated ID and timestamps.
    """
    id: str # The custom-generated patient ID
    registration_timestamp: datetime
    created_at: datetime

    class Config:
        from_attributes = True # Enable ORM mode (SQLAlchemy -> Pydantic)